package com.yolt.providers.n26.common.dto.ais;

public enum N26TransactionStatus {
    INVALID_STATUS, PENDING, PROCESSING, SUCCESS, PENDING_EXTERNAL_AUTHORIZATION, FAILURE_CANCELED,
    FAILURE_INSUFFICIENT_FUNDS, FAILURE_INVALID_CURRENCY, FAILURE_PERMISSION_DENIED, FAILURE_QUOTE_EXPIRED,
    FAILURE_INVALID_AMOUNT, FAILURE_INVALID_QUOTE, FAILURE_EXPIRED, FAILURE_GENERIC, SENT, INITIATED
}
