package com.yolt.providers.openbanking.ais.permanenttsbgroup;

import com.yolt.providers.common.cryptography.JwsSigningResult;

public class PermanentTsbGroupJwsSigningResult implements JwsSigningResult {

    private static final String ENCODED_SIGNATURE = "eyJhbGciOiJQUzI1NiJ9.eyJpYXQiOjEyMywiZXhwIjo0NTYsImp0aSI6IjFiMmRhNDQ3LTMzNTAtNDgyNi1hYWM5LTE4YmVlOGNlNjRhMiIsIk9yZ2FuaXNhdGlvbl9OYW1lIjoic3RyaW5nIiwiT3JnYW5pc2F0aW9uX0Rlc2NyaXB0aW9uIjoic3RyaW5nIiwiT3JnYW5pc2F0aW9uX1dlYnNpdGUiOiJzdHJpbmcgIiwiQXBwbGljYXRpb25fTmFtZSI6InN0cmluZyIsIkFwcGxpY2F0aW9uX0Rlc2NyaXB0aW9uIjoic3RyaW5nIiwiUmVkaXJlY3RfVVJJIjoic3RyaW5nIiwiQnVzaW5lc3NfQ29udGFjdF9OYW1lIjoic3RyaW5nIiwiQnVzaW5lc3NfQ29udGFjdF9FbWFpbCI6InN0cmluZyIsIkJ1c2luZXNzX0NvbnRhY3RfUGhvbmUiOiJzdHJpbmciLCJUZWNobmljYWxfQ29udGFjdF9OYW1lIjoic3RyaW5nIiwiVGVjaG5pY2FsX0NvbnRhY3RfRW1haWwiOiJzdHJpbmciLCJUZWNobmljYWxfQ29udGFjdF9QaG9uZSI6InN0cmluZyJ9.wExMPOLxA8_AcPg8Cdd5Ezoi_rVzSF1AgnmN1sNBA9o3H-xZRsgZ9rMupmBo4itfL8YTvPV1d6SRC9FRNgZV1A668r1fVQyc2yb8vZdeLM5ZkfAXrkbJnWuXrIxjcwJ711LbPfxtSceUCQJroOOZQDUsi6ld3jaBTSrjiofs9nirIaq_Q5sjjqeWLeh0rMZKeY1Z8XcbRgc24fSrcrAkRNL3Tw5j0NJsJF8PsDtHp0RHgvzV2lSfUp5gsqNvzRWUtOO7aMqyvA4L4GLKA8xftIcW7pdmwB1zv55CMpVL2pa1G0xFMUwMr5owEVHbH-pqGkIKAa4T4GBYaWwA0hfQ";

    @Override
    public String getCompactSerialization() {
        return ENCODED_SIGNATURE;
    }

    @Override
    public String getDetachedContentCompactSerialization() {
        return ENCODED_SIGNATURE;
    }
}
