{
  "swagger": "2.0",
  "info": {
    "title": "Alpha Bank - WEB Banking API",
    "description": "The ALPHA WEB Banking Account, Payment and Funds Confirmation APIs are PSD2 Compliant APIs providing information about the accounts (products) of a WEB Banking subscriber of the Alpha Bank, as well as payment initiation functionality. \nBoth account information and lists of transactions can be acquired, along with direct-debits, standing orders, etc.\n",
    "termsOfService": "https://developer.api.alphabank.gr/media/ryzpmllz/alphabankgroupproviderterms.pdf",
    "version": "1.3.4"
  },
  "host": "gw.api.alphabank.eu",
  "basePath": "/api/sandbox",
  "schemes": [
    "https"
  ],
  "tags": [
    {
      "name": "Accounts",
      "description": "Provides Account and Transaction information.\n"
    },
    {
      "name": "Payments",
      "description": "This API implements the protocol which is necessary in order a transfer or payment transaction to be initiated and monitored.\n"
    },
    {
      "name": "FundsConfirmation",
      "description": "Provides confirmation for the availability of funds on a specific account.\n"
    },
    {
      "name": "OpenData",
      "description": "Offers access to Open Bank Data including Branch information, ATMs and Currency rates.\n"
    }
  ],
  "paths": {
    "/accounts/v1/account-requests": {
      "post": {
        "summary": "Ask for an account request",
        "tags": [
          "Accounts"
        ],
        "description": "Ask for the generation of an account request. The account request is a 'resource' representing the intent of the client application to ask for account and transaction information. This intent must be authorised by the end user in order for the client to acquire the access-token necessary to call any of the relative API operations. The autorization of the intent is performed using the \"request\" parameter (query argument) at the authorize request. \n",
        "operationId": "CreateAccountRequest",
        "security": [
          {
            "TPPSec": [
              "account-info-setup"
            ]
          }
        ]
      }
    },
    "/accounts/v1/account-requests/{AccountRequestId}": {
      "get": {
        "summary": "Get an account request",
        "tags": [
          "Accounts"
        ],
        "description": "Return the Account Request intent object given its Id.\n",
        "operationId": "GetAccountRequest",
        "security": [
          {
            "TPPSec": [
              "account-info-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete an account request",
        "tags": [
          "Accounts"
        ],
        "description": "Delete an account request",
        "operationId": "DeleteAccountRequest",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/details": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get All Accounts",
        "description": "Get all accounts of the authenticated subscriber.",
        "operationId": "GetAllAcounts",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/details/cards": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get All Cards",
        "description": "Get all cards of the authenticated subscriber.",
        "operationId": "GetAllAcountsCards",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/details/deposit": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get All Deposit Accounts",
        "description": "Get all deposit accounts of the authenticated subscriber.",
        "operationId": "GetAllAcountsDeposit",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/balances": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Balances",
        "description": "Get balances related to all customer accounts",
        "operationId": "GetBalances",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/details": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Account",
        "description": "Get an account",
        "operationId": "GetAccount",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/standing-orders": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get account standing orders",
        "description": "Get the standing orders defined for the account with basic information. For detailed information about a specific order there is another endpoint to obtain detailed information about a standing order.",
        "operationId": "GetAccountStandingOrders",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/standing-orders/{StandingOrderId}": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get detailed information about a specific standing order",
        "description": "Get detailed information about a specific standing order. In order to obtain a list of standing orders there is a separate endpoint which provides basic info for each standing order.",
        "operationId": "GetAccountStandingOrdersDetails",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/direct-debits": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get account direct debits",
        "description": "Get the direct debits defined for the account with basic information. For detailed information about a specific direct debit there is another endpoint to obtain detailed information about a direct debit.",
        "operationId": "GetAccountDirectDebits",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/direct-debits/{DirectDebitId}": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get account direct debit",
        "description": "Get detailed information about a specific direct debit. In order to obtain a list of direct debits there is a separate endpoint which provides basic info for each direct debit.",
        "operationId": "GetAccountDirectDebit",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/balances": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Account Balances",
        "description": "Get balances related to an account",
        "operationId": "GetAccountBalances",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/beneficiaries": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Account Beneficiaries",
        "description": "Get the beneficiaries related to an account",
        "operationId": "GetAccountBeneficiaries",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/transactions": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Account Transactions",
        "description": "Get transactions related to an account",
        "operationId": "GetAccountTransactions",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/accounts/v1/{AccountId}/pending-transfers": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Account Pending Transfers",
        "description": "Get pending transactions related to an account that are scheduled to execute in the future.",
        "operationId": "GetAccountPendingTransactions",
        "security": [
          {
            "PSUSec": [
              "account-info"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/domestic": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a single domestic transfer intent object",
        "description": "Create a single domestic transfer intent object",
        "operationId": "CreateSingleDomesticTransfer",
        "security": [
          {
            "TPPSec": [
              "transfer-setup"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/domestic/{TransferRequestId}": {
      "get": {
        "summary": "Get a domestic transfer request",
        "tags": [
          "Payments"
        ],
        "description": "Return the Domestic Transfer Request intent object given its Id.\n",
        "operationId": "GetDomesticTransferRequest",
        "security": [
          {
            "TPPSec": [
              "transfer-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a domestic transfer request",
        "tags": [
          "Payments"
        ],
        "description": "Delete a domestic transfer request",
        "operationId": "DeleteDomesticTransferRequest",
        "security": [
          {
            "PSUSec": [
              "transfer"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/domestic/submissions": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a domestic transfer submission",
        "description": "Submit a previously setup domestic transfer",
        "operationId": "CreateDomesticTransferSubmission",
        "security": [
          {
            "PSUSec": [
              "transfer"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/domestic/submissions/{TransferSubmissionId}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get a domestic transfer submission",
        "description": "Get a previously setup domestic transfer",
        "operationId": "GetDomesticTransferSubmission",
        "security": [
          {
            "TPPSec": [
              "transfer-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a domestic transfer submission",
        "tags": [
          "Payments"
        ],
        "description": "Delete a domestic transfer submission",
        "operationId": "DeleteDomesticTransferSubmission",
        "security": [
          {
            "PSUSec": [
              "transfer-delete"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/international": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a single international transfer intent object",
        "description": "Create a single international transfer intent object",
        "operationId": "CreateSingleInternationalTransfer",
        "security": [
          {
            "TPPSec": [
              "transfer-setup"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/international/{TransferRequestId}": {
      "get": {
        "summary": "Get an international transfer request",
        "tags": [
          "Payments"
        ],
        "description": "Return the International Transfer Request intent object given its Id.\n",
        "operationId": "GetInternationalTransferRequest",
        "security": [
          {
            "TPPSec": [
              "transfer-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete an international transfer request",
        "tags": [
          "Payments"
        ],
        "description": "Delete an international transfer request",
        "operationId": "DeleteInternationalTransferRequest",
        "security": [
          {
            "PSUSec": [
              "transfer"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/international/submissions": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create an international transfer submission",
        "description": "Submit a previously setup international transfer",
        "operationId": "CreateInternationalTransferSubmission",
        "security": [
          {
            "PSUSec": [
              "transfer"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/international/submissions/{TransferSubmissionId}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get an international transfer submission",
        "description": "Get a previously setup international transfer",
        "operationId": "GetInternationalTransferSubmission",
        "security": [
          {
            "TPPSec": [
              "transfer-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete an international transfer submission",
        "tags": [
          "Payments"
        ],
        "description": "Delete an international transfer submission",
        "operationId": "DeleteInternationalTransferSubmission",
        "security": [
          {
            "PSUSec": [
              "transfer-delete"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/account/{AccountId}/history": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get the transfer submissions history for the specific Account",
        "description": "Get the transfer submissions history",
        "operationId": "GetAccountTransferHistory",
        "security": [
          {
            "PSUSec": [
              "transfer-info"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/history": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get the payment history for defined time period",
        "description": "Get the payment history for time period",
        "operationId": "GetPaymentHistoryForPeriod",
        "security": [
          {
            "PSUSec": [
              "transfer-info"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Payments"
        ],
        "summary": "Revoke the payment history access",
        "description": "Revoke the payment history access",
        "operationId": "RevokePaymentHistoryForPeriod",
        "security": [
          {
            "PSUSec": [
              "transfer-info"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/mass": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a mass transfer intent object",
        "description": "Create a mass transfer intent object. Currently not available for Alpha Bank Cyprus.",
        "operationId": "CreateMassTransfer",
        "security": [
          {
            "TPPSec": [
              "mass-transfer-setup"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/mass/{MassTransferId}": {
      "get": {
        "summary": "Get a mass transfer request object",
        "tags": [
          "Payments"
        ],
        "description": "Returns the Mass Transfer Transfer List given its MassTransferId. Currently not available for Alpha Bank Cyprus.",
        "operationId": "GetMassTransferList",
        "security": [
          {
            "TPPSec": [
              "mass-transfer-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a mass transfer request object",
        "tags": [
          "Payments"
        ],
        "description": "Delete a mass transfer request. Currently not available for Alpha Bank Cyprus.",
        "operationId": "DeleteMassTransferRequest",
        "security": [
          {
            "PSUSec": [
              "mass-transfer-delete"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/mass/{MassTransferId}/transfers": {
      "put": {
        "tags": [
          "Payments"
        ],
        "summary": "Append additional transfers to a mass transfer intent object",
        "description": "Append additional transfers to a created mass transfer intent object given its massTransferId. Currently not available for Alpha Bank Cyprus.",
        "operationId": "AppendMassTransferList",
        "security": [
          {
            "TPPSec": [
              "mass-transfer-setup"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Payments"
        ],
        "summary": "Remove transfers from a mass transfer intent object",
        "description": "Remove existing transfers from a created mass transfer intent object given its massTransferId. Currently not available for Alpha Bank Cyprus.",
        "operationId": "ReduceMassTransferList",
        "security": [
          {
            "TPPSec": [
              "mass-transfer-setup"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/mass/submissions": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a mass transfer submission",
        "description": "Submit a previously setup mass transfer. Currently not available for Alpha Bank Cyprus.",
        "operationId": "CreateMassTransferSubmission",
        "security": [
          {
            "PSUSec": [
              "mass-transfer"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/mass/submissions/{MassTransferSubmissionId}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get a mass transfer submission object",
        "description": "Get a previously setup mass transfer. Currently not available for Alpha Bank Cyprus.",
        "operationId": "GetMassTransferSubmission",
        "security": [
          {
            "TPPSec": [
              "mass-transfer-setup"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/standing-orders": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a standing order intent object",
        "description": "Initiate the standing order creation process by creating an intent object. Currently not available for Alpha Bank Cyprus.",
        "operationId": "CreateStandingOrderSetup",
        "security": [
          {
            "TPPSec": [
              "stand-order-setup"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/standing-orders/submissions": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create a standing order submission",
        "description": "Submit a previously setup standing order. Currently not available for Alpha Bank Cyprus.",
        "operationId": "CreateStandingOrderSubmission",
        "security": [
          {
            "PSUSec": [
              "stand-order"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/standing-orders/{StandingOrderRequestId}": {
      "get": {
        "summary": "Get a standing order request",
        "tags": [
          "Payments"
        ],
        "description": "Return the Standing Order Request intent object given its Id. Currently not available for Alpha Bank Cyprus.\n",
        "operationId": "GetStandingOrderRequest",
        "security": [
          {
            "TPPSec": [
              "stand-order-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a standing order request",
        "tags": [
          "Payments"
        ],
        "description": "Delete a standing order request",
        "operationId": "DeleteStandingOrderRequest",
        "security": [
          {
            "PSUSec": [
              "stand-order"
            ]
          }
        ]
      }
    },
    "/payments/v1/transfers/standing-orders/submissions/{StandingOrderId}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get a standing order submission",
        "description": "Get a previously submitted standing order. Currently not available for Alpha Bank Cyprus.",
        "operationId": "GetStandingOrderSubmission",
        "security": [
          {
            "TPPSec": [
              "stand-order-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a standing order submission",
        "tags": [
          "Payments"
        ],
        "description": "Delete a standing order submission. Currently not available for Alpha Bank Cyprus.",
        "operationId": "DeleteStandingOrderSubmission",
        "security": [
          {
            "PSUSec": [
              "stand-order-delete"
            ]
          }
        ]
      }
    },
    "/funds-confirmation/v1/funds-confirmation-requests": {
      "post": {
        "summary": "Create a funds confirmation intent",
        "tags": [
          "FundsConfirmation"
        ],
        "description": "Ask for the generation of a funds confirmation request. The funds confirmation request is a 'resource' representing the intent of the client application to ask for the funds availability of a specific account. This intent must be authorised by the end user in order for the client to acquire the access-token necessary to call any of the relative API operations. The autorization of the intent is performed using the \"request\" parameter (query argument) at the authorize req[...]",
        "operationId": "CreateFundsConfirmationRequest",
        "security": [
          {
            "TPPSec": [
              "funds-confirm-setup"
            ]
          }
        ]
      }
    },
    "/funds-confirmation/v1/funds-confirmation-requests/{FundsRequestId}": {
      "get": {
        "summary": "Get a funds confirmation request",
        "tags": [
          "FundsConfirmation"
        ],
        "description": "Return the Funds Confirmation intent object given its Id.\n",
        "operationId": "GetFundsConfirmationRequest",
        "security": [
          {
            "TPPSec": [
              "funds-confirm-setup"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a funds confirmation request",
        "tags": [
          "FundsConfirmation"
        ],
        "description": "Delete a funds confirmation request",
        "operationId": "DeleteFundsConfirmationRequest",
        "security": [
          {
            "PSUSec": [
              "funds-confirm"
            ]
          }
        ]
      }
    },
    "/funds-confirmation/v1/funds-confirmations": {
      "post": {
        "summary": "Submit a funds confirmation request",
        "tags": [
          "FundsConfirmation"
        ],
        "description": "Given a specified amount, inquire about the funds availability of an account which has been previously given consent for\n",
        "operationId": "FundsConfirmationSubmission",
        "security": [
          {
            "PSUSec": [
              "funds-confirm"
            ]
          }
        ]
      }
    },
    "/open-data/v1/branches": {
      "get": {
        "summary": "Get the list of the Bank Branches",
        "tags": [
          "OpenData"
        ],
        "description": "Return the list of the Bank Branches.\n",
        "operationId": "GetBranches",
        "security": [
          {
            "TPPSec": [
              "open-data"
            ]
          }
        ]
      }
    },
    "/open-data/v1/atms": {
      "get": {
        "summary": "Get the list of the Bank ATMs",
        "tags": [
          "OpenData"
        ],
        "description": "Return the list of the Bank ATMs.\n",
        "operationId": "GetATMs",
        "security": [
          {
            "TPPSec": [
              "open-data"
            ]
          }
        ]
      }
    },
    "/open-data/v1/akps": {
      "get": {
        "summary": "Get the list of the Bank AKPs",
        "tags": [
          "OpenData"
        ],
        "description": "Return the list of the Bank AKPs.\n",
        "operationId": "GetAKPs",
        "security": [
          {
            "TPPSec": [
              "open-data"
            ]
          }
        ]
      }
    },
    "/open-data/v1/rates": {
      "get": {
        "summary": "Get the list of the latest currency rates",
        "tags": [
          "OpenData"
        ],
        "description": "Return the list of the currency rates.\n",
        "operationId": "GetRates",
        "security": [
          {
            "TPPSec": [
              "open-data"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "PSUSec": {
      "type": "oauth2",
      "flow": "accessCode",
      "tokenUrl": "https://gw.api.alphabank.eu/sandbox/auth/token",
      "authorizationUrl": "https://gw.api.alphabank.eu/sandbox/auth/authorize",
      "scopes": {
        "account-info": "Account Request scope",
        "transfer": "Payment/Transfer execution scope",
        "transfer-info": "Payment/Transfer submission information scope",
        "transfer-delete": "Payment/Transfer deletion information scope",
        "mass-transfer": "Mass Transfer execution scope",
        "mass-transfer-delete": "Mass Transfer deletion information scope",
        "stand-order": "Standing Order Submission scope",
        "stand-order-delete": "Order Submission deletion scope",
        "funds-confirm": "Funds Confirmation scope"
      },
      "description": "OAuth2 flow, it is required when the PSU needs to perform authentication with the Alpha BANK when a TPP wants to access an Alpha BANK resource owned by the PSU"
    },
    "TPPSec": {
      "type": "oauth2",
      "flow": "application",
      "tokenUrl": "https://gw.api.alphabank.eu/sandbox/auth/token",
      "scopes": {
        "account-info-setup": "permission to create an account request intent object",
        "transfer-setup": "permission to create a payment/transfer request intent object",
        "stand-order-setup": "permission to create a standing order request intent object",
        "mass-transfer-setup": "permission to create a mass transfer request intent object",
        "open-data": "permission to access Open Bank Data",
        "funds-confirm-setup": "permission to create a funds confirmation request intent object"
      },
      "description": "TPP client credential authorisation flow for intent object"
    }
  }
}